# Generated by Django 5.0.9 on 2024-09-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twf", "0018_collectionitem_review_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                help_text="The members of the project. Their roles can be adjustedin the user management section.",
                related_name="projects",
                to="twf.userprofile",
                verbose_name="Project Members",
            ),
        ),
    ]
