# Generated by Django 5.0.9 on 2024-09-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twf", "0019_alter_project_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="document_export_configuration",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="A dictionary of export configurations for documents.",
                verbose_name="Document Export Configuration",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="page_export_configuration",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="A dictionary of export configurations for pages.",
                verbose_name="Page Export Configuration",
            ),
        ),
    ]
