# Generated by Django 5.0.9 on 2024-09-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twf", "0020_project_document_export_configuration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="is_parked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="document",
            name="workflow_remarks",
            field=models.TextField(blank=True, default=""),
        ),
    ]
