# Generated by Django 5.0.9 on 2024-09-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twf", "0021_document_is_parked_document_workflow_remarks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="is_parked",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
