# Generated by Django 5.0.9 on 2024-09-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twf", "0027_alter_task_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
