# Generated by Django 5.0.9 on 2024-11-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twf", "0030_prompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="conf_credentials",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="A dictionary of configuration credentials.",
                verbose_name="Configuration Credentials",
            ),
        ),
    ]
