# Generated by Django 5.0.9 on 2024-11-02 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("twf", "0034_remove_project_document_export_configuration_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="date_normalization_configuration",
        ),
    ]
