# Generated by Django 5.0.9 on 2024-11-02 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("twf", "0035_remove_project_date_normalization_configuration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="document_metadata_fields",
        ),
        migrations.RemoveField(
            model_name="project",
            name="page_metadata_fields",
        ),
    ]
