# Generated by Django 5.0.9 on 2024-11-02 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("twf", "0036_remove_project_document_metadata_fields_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="ignored_tag_types",
        ),
        migrations.RemoveField(
            model_name="project",
            name="tag_type_translator",
        ),
    ]
