# Generated by Django 5.0.9 on 2024-11-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twf", "0038_userprofile_affiliation_userprofile_orc_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection",
            options={"ordering": ["title"]},
        ),
        migrations.AlterField(
            model_name="collection",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="collectionitem",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
