# Generated by Django 5.0.9 on 2024-11-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twf", "0039_alter_collection_options_alter_collection_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="meta",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
