# Generated by Django 5.0.9 on 2024-12-04 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("twf", "0042_document_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workflow",
            old_name="assigned_items",
            new_name="assigned_document_items",
        ),
    ]
