# Generated by Django 5.0.11 on 2025-01-30 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("twf", "0045_alter_collectionitem_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="clearance_level",
        ),
    ]
