# Generated by Django 5.0.11 on 2025-01-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twf", "0046_remove_userprofile_clearance_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="permissions",
            field=models.JSONField(default=dict),
        ),
    ]
