# Generated by Django 5.0.11 on 2025-02-01 21:22

import twf.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twf", "0048_alter_collection_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="xml_file",
            field=models.FileField(
                max_length=255, upload_to=twf.models.page_directory_path
            ),
        ),
    ]
