# Generated by Django 5.0.11 on 2025-04-12 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twf", "0057_remove_note_user_note_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="twf.project",
            ),
        ),
    ]
