# Generated by Django 5.0.11 on 2025-04-27 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("twf", "0060_exportconfiguration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="conf_export",
        ),
    ]
