# Generated by Django 5.0.11 on 2025-04-27 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twf", "0061_remove_project_conf_export"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="export",
            name="export_type",
        ),
        migrations.RemoveField(
            model_name="export",
            name="project",
        ),
        migrations.AddField(
            model_name="export",
            name="export_configuration",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exports",
                to="twf.exportconfiguration",
            ),
            preserve_default=False,
        ),
    ]
