# Generated by Django 5.0.11 on 2025-05-04 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("twf", "0062_remove_export_export_type_remove_export_project_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exportconfiguration",
            name="is_default",
        ),
        migrations.AddField(
            model_name="exportconfiguration",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="exportconfiguration",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
