# Generated by Django 6.0.1 on 2026-01-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twf', '0067_add_pagetag_position_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_ignored',
            field=models.BooleanField(default=False),
        ),
    ]
