# Generated by Django 6.0.1 on 2026-06-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twf', '0068_document_is_ignored'),
    ]

    operations = [
        # These columns already exist in the database; wrap in SeparateDatabaseAndState
        # so Django's ORM state is updated without attempting to ALTER the table.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='task',
                    name='category',
                    field=models.CharField(blank=True, max_length=100, null=True),
                ),
                migrations.AddField(
                    model_name='task',
                    name='failed_items',
                    field=models.IntegerField(default=0),
                ),
                migrations.AddField(
                    model_name='task',
                    name='processed_items',
                    field=models.IntegerField(default=0),
                ),
                migrations.AddField(
                    model_name='task',
                    name='successful_items',
                    field=models.IntegerField(default=0),
                ),
                migrations.AddField(
                    model_name='task',
                    name='task_type',
                    field=models.CharField(blank=True, default='', max_length=255),
                ),
                migrations.AddField(
                    model_name='task',
                    name='total_items',
                    field=models.IntegerField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='task',
                    name='workflow_steps',
                    field=models.JSONField(blank=True, default=list),
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('needs_tk_work', 'Needs Correction on Transkribus'), ('reviewed', 'Reviewed')], default='open', max_length=20),
        ),
    ]
