# Generated by Django 6.0.1 on 2026-02-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twf", "0068_document_is_ignored"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagetag",
            name="is_reserved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workflow",
            name="assigned_tag_items",
            field=models.ManyToManyField(
                blank=True, related_name="workflows", to="twf.pagetag"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("needs_tk_work", "Needs Correction on Transkribus"),
                    ("reviewed", "Reviewed"),
                ],
                default="open",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="workflow_type",
            field=models.CharField(
                choices=[
                    ("review_documents", "Review Documents"),
                    ("review_collection", "Review Collection"),
                    ("supervised_dictionary", "Supervised Dictionary Workflow"),
                    ("review_tags_grouping", "Review Tag Grouping"),
                    ("review_tags_dates", "Review Date Normalization"),
                ],
                max_length=50,
            ),
        ),
    ]
