# Generated by Django 6.0.1 on 2026-02-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twf", "0069_pagetag_is_reserved_workflow_assigned_tag_items_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
