# Generated by Django 6.0.1 on 2026-02-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twf", "0070_workflow_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflow",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
