# Generated by Django 6.0.1 on 2026-02-04 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twf", "0071_alter_workflow_metadata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TagEnrichment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("variation", models.CharField(max_length=255)),
                ("enrichment_type", models.CharField(max_length=50)),
                ("normalized_value", models.CharField(max_length=500)),
                ("enrichment_data", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["variation"],
            },
        ),
        migrations.AddField(
            model_name="pagetag",
            name="tag_enrichment_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="twf.tagenrichment",
            ),
        ),
        migrations.AddIndex(
            model_name="tagenrichment",
            index=models.Index(
                fields=["enrichment_type", "variation"],
                name="twf_tagenri_enrichm_86aaf0_idx",
            ),
        ),
    ]
