# Generated by Django 6.0.1 on 2026-02-04 19:38

from django.db import migrations


def migrate_dates_forward(apps, schema_editor):
    """Migrate DateVariation records to TagEnrichment."""
    DateVariation = apps.get_model("twf", "DateVariation")
    TagEnrichment = apps.get_model("twf", "TagEnrichment")
    PageTag = apps.get_model("twf", "PageTag")

    # Create TagEnrichment for each DateVariation
    for date_var in DateVariation.objects.all():
        enrichment = TagEnrichment.objects.create(
            variation=date_var.variation,
            enrichment_type="date",
            normalized_value=date_var.edtf_of_normalized_variation,
            enrichment_data={
                "edtf": date_var.edtf_of_normalized_variation,
                "original_normalized_variation": date_var.normalized_variation,
            },
            created_at=date_var.created_at,
            modified_at=date_var.modified_at,
        )

        # Copy user fields if they exist
        if hasattr(date_var, "created_by"):
            enrichment.created_by = date_var.created_by
        if hasattr(date_var, "modified_by"):
            enrichment.modified_by = date_var.modified_by

        enrichment.save()

        # Update all tags pointing to this DateVariation
        PageTag.objects.filter(date_variation_entry=date_var).update(
            tag_enrichment_entry=enrichment
        )


def migrate_dates_backward(apps, schema_editor):
    """Reverse migration: clear tag_enrichment_entry for date types."""
    PageTag = apps.get_model("twf", "PageTag")
    TagEnrichment = apps.get_model("twf", "TagEnrichment")

    # Clear tag_enrichment_entry for tags that had date variations
    PageTag.objects.filter(tag_enrichment_entry__enrichment_type="date").update(
        tag_enrichment_entry=None
    )

    # Delete date enrichments
    TagEnrichment.objects.filter(enrichment_type="date").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("twf", "0072_create_tag_enrichment"),
    ]

    operations = [
        migrations.RunPython(migrate_dates_forward, migrate_dates_backward),
    ]
