# Generated by Django 6.0.1 on 2026-02-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twf", "0073_migrate_dates_to_enrichments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflow",
            name="workflow_type",
            field=models.CharField(
                choices=[
                    ("review_documents", "Review Documents"),
                    ("review_collection", "Review Collection"),
                    ("supervised_dictionary", "Supervised Dictionary Workflow"),
                    ("review_tags_grouping", "Review Tag Grouping"),
                    ("review_tags_dates", "Review Date Normalization"),
                    ("review_tags_enrichment", "Review Tag Enrichment"),
                ],
                max_length=50,
            ),
        ),
    ]
