# Generated by Django 6.0.1 on 2026-02-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twf", "0074_alter_workflow_workflow_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="assigned_page_items",
            field=models.ManyToManyField(
                blank=True, related_name="workflows", to="twf.page"
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="workflow_type",
            field=models.CharField(
                choices=[
                    ("review_documents", "Review Documents"),
                    ("review_collection", "Review Collection"),
                    ("supervised_dictionary", "Supervised Dictionary Workflow"),
                    ("review_tags_grouping", "Review Tag Grouping"),
                    ("review_tags_dates", "Review Date Normalization"),
                    ("review_tags_enrichment", "Review Tag Enrichment"),
                    ("review_metadata_documents", "Review Document Metadata"),
                    ("review_metadata_pages", "Review Page Metadata"),
                ],
                max_length=50,
            ),
        ),
    ]
