# Generated by Django 6.0.1 on 2026-02-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twf", "0075_workflow_assigned_page_items_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagetag",
            name="enrichment",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
