# Generated by Django 6.0.1 on 2026-02-12 16:13

from django.db import migrations


def migrate_tag_enrichments(apps, schema_editor):
    """
    Migrate data from TagEnrichment model to PageTag.enrichment JSONField.

    For each PageTag with a tag_enrichment_entry, copy the enrichment data to
    the enrichment field in the format:
    {
        enrichment_type: {
            "normalized_value": normalized_value,
            "enrichment_data": enrichment_data
        }
    }
    """
    PageTag = apps.get_model("twf", "PageTag")
    TagEnrichment = apps.get_model("twf", "TagEnrichment")

    # Count tags with enrichment entries
    tags_with_enrichment = PageTag.objects.filter(
        tag_enrichment_entry__isnull=False
    ).select_related('tag_enrichment_entry')

    total_count = tags_with_enrichment.count()
    migrated_count = 0

    print(f"Found {total_count} tags with enrichment entries to migrate")

    for tag in tags_with_enrichment:
        enrichment_entry = tag.tag_enrichment_entry

        # Initialize enrichment dict if needed
        if tag.enrichment is None:
            tag.enrichment = {}

        # Add enrichment data in the new format
        tag.enrichment[enrichment_entry.enrichment_type] = {
            "normalized_value": enrichment_entry.normalized_value,
            "enrichment_data": enrichment_entry.enrichment_data or {},
        }

        tag.save(update_fields=['enrichment'])
        migrated_count += 1

        if migrated_count % 100 == 0:
            print(f"Migrated {migrated_count}/{total_count} tags...")

    print(f"Successfully migrated {migrated_count} tag enrichments")

    # Validation: check that all tags now have the enrichment data
    validation_count = PageTag.objects.filter(
        tag_enrichment_entry__isnull=False,
        enrichment__isnull=False
    ).count()

    if validation_count != total_count:
        raise Exception(
            f"Validation failed! Expected {total_count} tags with enrichment, "
            f"but found {validation_count}. Rolling back migration."
        )

    print(f"Validation passed: {validation_count} tags have enrichment data")


def reverse_migration(apps, schema_editor):
    """
    Reverse the migration by clearing enrichment data.
    Note: This doesn't restore TagEnrichment entries, just clears the enrichment field.
    """
    PageTag = apps.get_model("twf", "PageTag")

    count = PageTag.objects.filter(enrichment__isnull=False).update(enrichment={})
    print(f"Cleared enrichment data from {count} tags")


class Migration(migrations.Migration):

    dependencies = [
        ("twf", "0076_add_pagetag_enrichment_field"),
    ]

    operations = [
        migrations.RunPython(migrate_tag_enrichments, reverse_migration),
    ]
