# Generated by Django 6.0.1 on 2026-02-13 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twf", "0077_migrate_tag_enrichment_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflow",
            name="workflow_type",
            field=models.CharField(
                choices=[
                    ("review_documents", "Review Documents"),
                    ("review_collection", "Review Collection"),
                    ("supervised_dictionary", "Supervised Dictionary Workflow"),
                    ("review_tags_grouping", "Review Tag Grouping"),
                    ("review_tags_dates", "Review Date Normalization"),
                    ("review_tags_enrichment", "Review Tag Enrichment"),
                    ("review_dictionary_enrichment", "Review Dictionary Enrichment"),
                    ("review_metadata_documents", "Review Document Metadata"),
                    ("review_metadata_pages", "Review Page Metadata"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="AIConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Display name, e.g., 'Document Summarizer (GPT-4)'",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="What this configuration is used for"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI (ChatGPT)"),
                            ("anthropic", "Anthropic (Claude)"),
                            ("genai", "Google (Gemini)"),
                            ("mistral", "Mistral AI"),
                            ("deepseek", "DeepSeek"),
                            ("qwen", "Qwen"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        help_text="Model identifier, e.g., 'gpt-4', 'claude-3-opus-20240229'",
                        max_length=100,
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        help_text="API key for this provider", max_length=500
                    ),
                ),
                (
                    "system_role",
                    models.TextField(help_text="System role/instructions for the AI"),
                ),
                (
                    "prompt_template",
                    models.TextField(
                        help_text="Prompt template with {placeholders} for context. Example: 'Summarize: {document_text}'"
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        blank=True,
                        default=0.5,
                        help_text="Sampling temperature (0.0-2.0)",
                        null=True,
                    ),
                ),
                (
                    "max_tokens",
                    models.IntegerField(
                        blank=True,
                        default=2048,
                        help_text="Maximum tokens to generate",
                        null=True,
                    ),
                ),
                (
                    "top_p",
                    models.FloatField(
                        blank=True,
                        default=1.0,
                        help_text="Nucleus sampling threshold",
                        null=True,
                    ),
                ),
                (
                    "frequency_penalty",
                    models.FloatField(
                        blank=True,
                        default=0.0,
                        help_text="Frequency penalty (-2.0 to 2.0)",
                        null=True,
                    ),
                ),
                (
                    "presence_penalty",
                    models.FloatField(
                        blank=True,
                        default=0.0,
                        help_text="Presence penalty (-2.0 to 2.0)",
                        null=True,
                    ),
                ),
                (
                    "seed",
                    models.IntegerField(
                        blank=True,
                        help_text="Random seed for deterministic sampling",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Disable to hide from workflow selectors",
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(
                        default=0, help_text="Track how often this config is used"
                    ),
                ),
                (
                    "collection_context",
                    models.ManyToManyField(
                        blank=True, related_name="ai_configs", to="twf.collectionitem"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document_context",
                    models.ManyToManyField(
                        blank=True, related_name="ai_configs", to="twf.document"
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "page_context",
                    models.ManyToManyField(
                        blank=True, related_name="ai_configs", to="twf.page"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_configs",
                        to="twf.project",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("project", "name")},
            },
        ),
    ]
