# Generated by Django 6.0.1 on 2026-02-14 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("twf", "0078_alter_workflow_workflow_type_aiconfiguration"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Prompt",
        ),
    ]
