# Generated by Django 6.0.1 on 2026-02-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twf", "0080_enhance_task_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="dictionaryentry",
            name="is_parked",
            field=models.BooleanField(default=False),
        ),
    ]
