# Generated by Django 6.0.1 on 2026-02-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twf", "0081_dictionaryentry_is_parked"),
    ]

    operations = [
        migrations.AddField(
            model_name="dictionaryentry",
            name="review_status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("reviewed", "Reviewed")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("STARTED", "Started"),
                    ("SUCCESS", "Success"),
                    ("FAILURE", "Failure"),
                    ("PROGRESS", "Progress"),
                    ("CANCELED", "Cancelled"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="workflow_type",
            field=models.CharField(
                choices=[
                    ("review_documents", "Review Documents"),
                    ("review_collection", "Review Collection"),
                    ("supervised_dictionary", "Supervised Dictionary Workflow"),
                    ("review_tags_grouping", "Review Tag Grouping"),
                    ("review_tags_dates", "Review Date Normalization"),
                    ("review_tags_enrichment", "Review Tag Enrichment"),
                    ("review_dictionary_enrichment", "Review Dictionary Enrichment"),
                    ("review_dictionary_entries", "Review Dictionary Entries"),
                    ("review_metadata_documents", "Review Document Metadata"),
                    ("review_metadata_pages", "Review Page Metadata"),
                ],
                max_length=50,
            ),
        ),
    ]
