# Generated by Django 6.0.1 on 2026-06-23 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twf', '0069_add_task_type_fields'),
        ('twf', '0082_add_review_status_to_dictionary_entry'),
    ]

    operations = [
    ]
