# Generated by Django 6.0.1 on 2026-06-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twf", "0083_merge_20260623_1031"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("bulk_delete", "Bulk Delete"),
                    ("import", "Import/Extract"),
                    ("export", "Export"),
                    ("ai_processing", "AI Processing"),
                    ("enrichment", "Enrichment"),
                    ("workflow", "Workflow"),
                    ("system", "System"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("instant", "Instant"),
                    ("celery", "Celery Background Task"),
                    ("workflow", "Workflow"),
                ],
                default="celery",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="workflow_steps",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
